# Generated by Django 2.2.6 on 2019-10-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=20)),
                ('roomNo', models.CharField(max_length=10)),
                ('blockNo', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('phoneNo', models.CharField(max_length=15)),
                ('profilePic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGiven', models.DateTimeField(auto_now_add=True)),
                ('readyToPick', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laundryApi.CustomerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGiven', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laundryApi.CustomerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLaundryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGiven', models.DateTimeField(auto_now_add=True)),
                ('datePickup', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laundryApi.CustomerDetails')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laundryApi.ItemDetails')),
            ],
        ),
    ]
