# Generated by Django 2.2.6 on 2019-10-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='rollNo',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='profilePic',
            field=models.CharField(max_length=25),
        ),
    ]
