# Generated by Django 2.2.6 on 2019-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0003_auto_20191022_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlaundrydetails',
            name='datePickup',
            field=models.DateTimeField(default=None),
        ),
    ]
