# Generated by Django 2.2.6 on 2019-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0004_auto_20191022_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='blockNo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phoneNo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='profilePic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='roomNo',
            field=models.CharField(max_length=100),
        ),
    ]
