# Generated by Django 2.2.6 on 2019-10-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0004_auto_20191022_1422'),
        ('laundryApi', '0005_auto_20191022_1800'),
    ]

    operations = [
    ]
