# Generated by Django 2.2.6 on 2019-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0006_merge_20191023_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlaundrydetails',
            name='datePickup',
            field=models.DateTimeField(),
        ),
    ]
