# Generated by Django 2.2.6 on 2019-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundryApi', '0007_auto_20191023_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlaundrydetails',
            name='datePickup',
            field=models.DateTimeField(blank=True),
        ),
    ]
